### ISSUE TITLE
Wrong VOTAble syntax in polarization example 

### ISSUE THREAD

**Issue by Bonnarel** [ivoa-std/SODA#1]
ON January the 16th 2020 Alberto Micol discovered : 

Page 19 of the SODA standard shows:

```xml
<PARAM name="POL" ucd="meta.code;phys.polarization" datatype="char" arraysize="*" ''value=""> '<DESCRIPTION>Polarization states to be extracted.</DESCRIPTION> <VALUES>

<OPTION>I</OPTION>

<OPTION>V</OPTION> </VALUE>

</PARAM>
```

 

 

My understanding of the VOTable standard is that the correct way should instead be

(see the sentence

"All three MIN, MAX and OPTION sub-elements store their value corresponding to the minimum, maximum, or ``special value'' in a value attribute."

In the paragraph at:  http://www.ivoa.net/documents/VOTable/20191021/REC-VOTable-1.4-20191021.html#sec:values ):

 
```xml
<PARAM name="POL" ucd="meta.code;phys.polarization" datatype="char" arraysize="*" value=""> <DESCRIPTION>Polarization states to be extracted.</DESCRIPTION> <VALUES>

<OPTION value="I"/>

<OPTION value="V"/>

</VALUE>

</PARAM> 
```

Alberto is perfectly right !!!

**Comment by pdowler** [comment]
This looks like a clear case of not ujsing VOTable correctly. Erratum.

**Comment by Bonnarel** [comment]
This has been fixed with SODA erratum 2
