### ISSUE TITLE
Wrong example for BAND interval MIN and MAX values

### ISSUE THREAD

**Issue by Bonnarel** [ivoa-std/SODA#2]
This appeared in a  discussion between Alberto Micol and Markus on the dal Mailing list

MIN and MAX  cannot be single values as in the example
It should be an array. But an array of what ?
An array of minimal values and an array of maximal values (Markus)
An array of minimal length interval and an array of maximal length interval (Alberto)

**Comment by pdowler** [comment]
Ambiguous or wrong example is most likely an erratum. I'll look at the current wording and VOtable spec and take sides asap.

**Comment by Bonnarel** [comment]
According to the discussion in ivoa-std/VOTabel#32, the MIN/MAX usage is considered here in the default case. This is explaind and solved in https://wiki.ivoa.net/twiki/bin/view/IVOA/SODA10Err3
